extensions:
- name: seq
  logPath: ./.logs

name: servicetemplate
network: tye-network
ingress:
    - name: Ingress
      bindings:
        - port: 50000
          protocol: https
          ip: '127.0.0.1'
      rules:
        - host: notification-api.dev.timetarget.com
          service: notification-api

services:
    - name: notification-api
      project: Notification/src/Notification.API/Notification.API.csproj
      bindings:
      - port: 51001
        protocol: https

    - name: mock-api
      project: Notification/tests/Mock.API/Mock.API.csproj
      bindings:
      - port: 51000
        protocol: http

    - name: SqlServer
      image: mcr.microsoft.com/mssql/server:2019-latest
      bindings:
      - connectionString: Data Source=localhost,1433;Initial Catalog=ServiceDB;Persist Security Info=True;User ID=sa;Password=${env:SA_PASSWORD}
        port: 1433
      env:
      - name: SA_PASSWORD
        value: M3rz0ug4!!!!
      - name: ACCEPT_EULA
        value: "Y"

    - name: Redis
      image: redis
      bindings:
      - port: 6379
        connectionString: "${host}:${port}"

    - name: DynamoDB
      image: "amazon/dynamodb-local:latest"
      args: -jar DynamoDBLocal.jar -inMemory -sharedDb
      bindings:
      - port: 8000
      env:
      - name: AWS_ACCESS_KEY_ID
        value: test
      - name: AWS_SECRET_ACCESS_KEY
        value: test
      - name: REGION
        value: ap-southeast-2
        
    - name: KMS
      image: nsmithuk/local-kms
      volumes:
         - source: "C:/"
           target: "/mnt/c"
      bindings:
      - port: 52002
      env:
      - name: KMS_REGION
        value: "ap-southeast-2"
      - name: KMS_SEED_PATH
        value: "/mnt/c/Dev/HF-Services/local-kms-seed.yaml"

    - name: Cognito
      image: jagregory/cognito-local:latest
      volumes:
         - source: "C:/mnt/c/.cognito"
           target: "/app/.cognito"
      bindings:
      - port: 9229

    - name: LocalStack
      image: "localstack/localstack:latest"
      bindings:
      - port: 4566
      env:
      - name: DEBUG
        value: "1"
      - name: SERVICES
        value: "logs"

    - name: Zipkin
      image: "openzipkin/zipkin"
      bindings:
      - port: 9411
        protocol: http
