# winget-config.yaml
Source:
  Name: winget

Sources:
  - msstore
  - winget

# Development Tools (IDEs, SDKs)
Applications:
  # JetBrains - IDE
  - Id: JetBrains.IntelliJIDEA.Community
    InstallerSwitches:
      Silent: "/S /norestart"
  # Microsoft - IDE
  - Id: Microsoft.VisualStudio.2022.Professional
    InstallerSwitches:
      Silent: "--quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.NetCoreTools --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.XamarinBuildTools"
  # Microsoft - Editor
  - Id: Microsoft.VisualStudioCode
    InstallerSwitches:
      Silent: "/S /norestart"
  # Google - IDE
  - Id: Google.AndroidStudio
    InstallerSwitches:
      Silent: "/S /norestart"

# DevOps and Infrastructure (CLI, Cloud Tools, Services)
  # Amazon - AWS CLI
  - Id: Amazon.AWSCLI
    InstallerSwitches:
      Silent: "/quiet /norestart"
  # Amazon - AWS SAM CLI
  - Id: Amazon.AWSSAMCLI
    InstallerSwitches:
      Silent: "/S /norestart"
  # Microsoft - PowerShell
  - Id: Microsoft.Powershell
    InstallerSwitches:
      Silent: "/quiet /norestart"
  # Microsoft - Windows Terminal
  - Id: Microsoft.WindowsTerminal
    InstallerSwitches:
      Silent: "/S /norestart"

# Database and Data Tools
  # Redis - NoSQL Database
  - Id: Redis.RedisInsight
    InstallerSwitches:
      Silent: "/S /norestart"
  # Amazon - NoSQL Workbench for DynamoDB
  - Id: Amazon.NoSQLWorkbench
    InstallerSwitches:
      Silent: "/S /norestart"
  # Microsoft - SQL Server Management Studio (SSMS)
  - Id: Microsoft.SQLServerManagementStudio
    InstallerSwitches:
      Silent: "/quiet /norestart"
  # Postman - API Testing Tool
  - Id: Postman.Postman
    InstallerSwitches:
      Silent: "/S /norestart"

# Runtime, SDKs, and Frameworks
  # Microsoft - .NET SDKs
  - Id: Microsoft.DotNet.SDK.6
    InstallerSwitches:
      Silent: "/quiet /norestart"
  - Id: Microsoft.DotNet.SDK.8
    InstallerSwitches:
      Silent: "/quiet /norestart"
  - Id: Microsoft.DotNet.SDK.9
    InstallerSwitches:
      Silent: "/quiet /norestart"
  # Microsoft - .NET Runtimes
  - Id: Microsoft.DotNet.Runtime.6
    InstallerSwitches:
      Silent: "/quiet /norestart"
  - Id: Microsoft.DotNet.Runtime.8
    InstallerSwitches:
      Silent: "/quiet /norestart"
  - Id: Microsoft.DotNet.Runtime.9
    InstallerSwitches:
      Silent: "/quiet /norestart"
  # Microsoft - .NET Framework 4.8 Runtime
  - Id: Microsoft.DotNetFramework.Runtime.4
    InstallerSwitches:
      Silent: "/quiet /norestart"
  # Microsoft - ASP.NET Core Runtimes
  - Id: Microsoft.DotNet.AspNetCore.6
    InstallerSwitches:
      Silent: "/quiet /norestart"
  - Id: Microsoft.DotNet.AspNetCore.8
    InstallerSwitches:
      Silent: "/quiet /norestart"
  - Id: Microsoft.DotNet.AspNetCore.9
    InstallerSwitches:
      Silent: "/quiet /norestart"
  # Eclipse Adoptium - Java Development Kit (JDK)
  - Id: EclipseAdoptium.Temurin.17.JDK
    InstallerSwitches:
      Silent: "/s /norestart"
  # Microsoft - NuGet Package Manager
  - Id: NuGet.NuGet
    InstallerSwitches:
      Silent: "/S /norestart"

# Version Control and Code Management
  # Git - Version Control
  - Id: Git.Git
    InstallerSwitches:
      Silent: "/VERYSILENT /NORESTART"
  # GitHub - GitHub Desktop
  - Id: GitHub.GitHubDesktop
    InstallerSwitches:
      Silent: "/S /norestart"

# Node.js and JavaScript Tooling
  # NVM for Windows - Node.js Version Manager
  - Id: CoreyButler.NVMforWindows
    InstallerSwitches:
      Silent: "/S /norestart"

# DevOps, Containerization, and Virtualization
  # Docker - Docker Desktop
  - Id: Docker.DockerDesktop
    InstallerSwitches:
      Silent: "/quiet /norestart"

# Note-Taking and Productivity
  # Obsidian - Knowledge Base and Note-Taking
  - Id: Obsidian.Obsidian
    InstallerSwitches:
      Silent: "/S /norestart"

# Post-install configuration steps
PostInstallScript:
  Script: |
    # Enable IIS features without restarting
    DISM /online /enable-feature /featurename:IIS-WebServerRole /all /norestart
    DISM /online /enable-feature /featurename:IIS-WebServerManagementTools /all /norestart
    DISM /online /enable-feature /featurename:IIS-ManagementConsole /all /norestart
    DISM /online /enable-feature /featurename:IIS-NetFxExtensibility45 /all /norestart
    DISM /online /enable-feature /featurename:IIS-ISAPIExtensions /all /norestart
    DISM /online /enable-feature /featurename:IIS-ISAPIFilter /all /norestart
    DISM /online /enable-feature /featurename:IIS-ASPNET45 /all /norestart
    DISM /online /enable-feature /featurename:IIS-CGI /all /norestart
    DISM /online /enable-feature /featurename:IIS-DefaultDocument /all /norestart
    DISM /online /enable-feature /featurename:IIS-DirectoryBrowsing /all /norestart
    DISM /online /enable-feature /featurename:IIS-HttpErrors /all /norestart
    DISM /online /enable-feature /featurename:IIS-StaticContent /all /norestart
    DISM /online /enable-feature /featurename:IIS-HttpLogging /all /norestart
    DISM /online /enable-feature /featurename:IIS-HttpCompressionStatic /all /norestart
    DISM /online /enable-feature /featurename:IIS-Security /all /norestart
    DISM /online /enable-feature /featurename:IIS-IPSecurity /all /norestart
    DISM /online /enable-feature /featurename:IIS-BasicAuthentication /all /norestart
    DISM /online /enable-feature /featurename:IIS-WindowsAuthentication /all /norestart
    DISM /online /enable-feature /featurename:IIS-DigestAuthentication /all /norestart
    DISM /online /enable-feature /featurename:IIS-URLAuthorization /all /norestart
    DISM /online /enable-feature /featurename:IIS-ClientCertificateMappingAuthentication /all /norestart
    DISM /online /enable-feature /featurename:IIS-IISCertificateMappingAuthentication /all /norestart
    DISM /online /enable-feature /featurename:IIS-CertProvider /all /norestart
    # Enable Hyper-V without restarting
    dism /online /enable-feature /featurename:Microsoft-Hyper-V-All /all /norestart
    # Enable WSL and install WSL 2
    wsl --install
    # Set WSL version to 2
    wsl --set-default-version 2
    # Install Ubuntu as the default Linux distro
    wsl --install -d Ubuntu
    # Use NVM to install Node.js LTS and update npm
    nvm install lts
    nvm use lts
    npm install -g npm
    # Install Angular globally via npm
    npm install -g @angular/cli
    # Install Visual Studio Code Extensions
    code --install-extension ms-dotnettools.csharp
    code --install-extension ms-dotnettools.csdevkit
    code --install-extension ms-dotnettools.vscodeintellicode-csharp
    code --install-extension ms-mssql.mssql
    code --install-extension ms-vscode-remote.remote-containers
    code --install-extension ms-vscode-remote.remote-wsl
    code --install-extension AmazonWebServices.aws-toolkit-vscode
    code --install-extension GitHub.copilot-chat
    code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
    code --install-extension ms-playwright.playwright
    code --install-extension ms-vscode.PowerShell
    # Install SonarLint for Visual Studio 2022
    "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\Microsoft\VsixInstaller.exe" /quiet /q /skuName:Pro /skuVersion:17.0 "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/sonarsource/vsextensions/sonarlint/5.2.0/vsix"
    # Install AWS Toolkit for Visual Studio 2022
    "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\Microsoft\VsixInstaller.exe" /quiet /q /skuName:Pro /skuVersion:17.0 "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AmazonWebServices/vsextensions/AWSToolkitforVisualStudio2022/1.22/vsix"
