# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#

extensions:
- name: seq
  logPath: ./.logs

name: servicetemplate
ingress:
    - name: ingress
      bindings:
        - port: 51000
      rules:
        - path: /A
          service: servicename-api
        - path: /B
          service: servicename-api
services:
    - name: servicename-api
      project: ServiceName.API/ServiceName.API.csproj
      bindings:
      - port: 51001
      replicas: 2

    #- name: SQL-Database
    #  image: mcr.microsoft.com/mssql/server:2019-latest
    #  bindings:
    #  - connectionString: Data Source=host.docker.internal,1433;Initial Catalog=ServiceDB;Persist Security Info=True;User ID=sa;Password=${env:SA_PASSWORD}
    #    port: 1433
    #  env:
    #  - name: SA_PASSWORD
    #    value: M3rz0ug4!!!!
    #  - name: ACCEPT_EULA
    #    value: Y

    - name: redis-cache
      image: redis
      bindings:
      - port: 6379
        connectionString: "${host}:${port}"
      args: "redis-cli -h redis MONITOR"

    # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html (Docker Tab)
    #aws --endpoint-url=http://localhost:52001 dynamodb create-table --table-name ServiceName_Setting --attribute-definitions AttributeName=TenantId,AttributeType=S --key-schema AttributeName=TenantId,KeyType=HASH --billing-mode PAY_PER_REQUEST
    - name: dynamodb-database
      image: "amazon/dynamodb-local:latest"
      args: -jar DynamoDBLocal.jar -sharedDb -dbPath /mnt/c/Temp/DynamoDB
      volumes:
         - source: "./"
           target: "/mnt/c/Temp/DynamoDB"
      bindings:
      - port: 8000
      env:
      - name: AWS_ACCESS_KEY_ID
        value: test
      - name: AWS_SECRET_ACCESS_KEY
        value: test
      - name: REGION
        value: ap-southeast-2
        
    #aws --endpoint-url=http://localhost:52002 kms --region ap-southeast-2 create-key --key-spec RSA_4096 --key-usage ENCRYPT_DECRYPT
    #aws --endpoint-url=http://localhost:52002 kms --region ap-southeast-2 list-keys
    - name: kms-local
      image: nsmithuk/local-kms
      volumes:
         - source: "./"
           target: "/mnt/c/Temp/Kms"
      bindings:
      - port: 52002